name: marketing-platform
region: nyc
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: marketing-platform
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  run_command: npm start
  source_dir: /